### ISSUE TITLE
Support the option to exclude EXIF stripping by directory

### ISSUE THREAD

**Issue by monksy** [stefmolin/exif-stripper#36]
**Is your feature request related to a problem? Please describe.**

There are plugins for Jekyll that will extract the EXIF info for photos and allow for you to pass them in in other places. Sometimes that might be as intended.

https://github.com/NiklasEi/jekyll-exif-data

**Describe the solution you'd like**

I would like for an configurable option to specify excluded directories that don't strip images.  A warning might be good in the console that the file is being skipped due to being in a particular directory.

Documentation updated for the configuration.

**Describe alternatives you've considered**

None.

**Additional context**

**Comment by stefmolin** [comment]
Hi there &ndash; this is controlled by your `.pre-commit-config.yaml` file. You can use the `exclude` option to provide a regular expression of directories to ignore:

```yaml
- repo: https://github.com/stefmolin/exif-stripper
  rev: 0.3.1
  hooks:
    - id: strip-exif
      exclude: (dir1|dir2)/.*
```

Be sure to check out the [pre-commit docs](https://pre-commit.com/#pre-commit-configyaml---hooks) for other options.
